# -*- mode: ruby -*-
# vi: set ft=ruby :

$USER_NAME = 'as'

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.cpus = 4
    vb.memory = "4096"
  end

  config.vm.provision "shell", inline: "sudo apt-get update"
  config.vm.provision :shell, :path => "setup.sh", :args => [$USER_NAME]

  config.landrush.enabled = true
  config.vm.define vm_name = "asvm" do |c|
      c.vm.hostname = vm_name
      config.landrush.tld = vm_name
      c.vm.network "private_network", ip: "192.168.99.100"
      c.vm.network "forwarded_port", guest: 30000, host: 30000
  end
  config.landrush.host 'minikube', '192.168.99.100'

end

