# -*- mode: ruby -*-
# vi: set ft=ruby :

$vm_cpus = `cat /proc/cpuinfo | grep 'core id' | sort -u | wc -l`.to_i
if $vm_cpus < 1
    $vm_cpus = `nproc`.to_i
end
$vm_master_mem = (ENV['KUBERNETES_MASTER_MEMORY'] || ENV['KUBERNETES_MEMORY'] || 1280).to_i
$vm_node_mem = (ENV['KUBERNETES_NODE_MEMORY'] || ENV['KUBERNETES_MEMORY'] || 2048).to_i

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = false

  config.vm.provision :shell, :path => "install.sh"

  config.hostmanager.enabled = true
  config.hostmanager.manage_guest = true

  def customize_vm(config, vm_mem)
    # Don't attempt to update Virtualbox Guest Additions (requires gcc)
    if Vagrant.has_plugin?("vagrant-vbguest") then
      config.vbguest.auto_update = false
    end
    # Finally, fall back to VirtualBox
    config.vm.provider :virtualbox do |v, override|
      #setvmboxandurl(override, :virtualbox)
      v.memory = vm_mem # v.customize ["modifyvm", :id, "--memory", vm_mem]
      v.cpus = $vm_cpus # v.customize ["modifyvm", :id, "--cpus", $vm_cpus]
      
      # Use faster paravirtualized networking
      v.customize ["modifyvm", :id, "--nictype1", "virtio"]
      v.customize ["modifyvm", :id, "--nictype2", "virtio"]
    end
  end

  # Kubernetes master
  config.vm.define "master" do |c|
      customize_vm c, $vm_master_mem

      c.vm.hostname = "master"
      c.vm.network "private_network", ip: "192.168.77.10"
      c.vm.network "forwarded_port", guest: 8001, host: 8001
      c.vm.network "forwarded_port", guest: 2379, host: 2379
      c.vm.network "forwarded_port", guest: 2380, host: 2380
      c.vm.network "forwarded_port", guest: 10250, host: 10250
      c.vm.network "forwarded_port", guest: 10251, host: 10251
      c.vm.network "forwarded_port", guest: 10252, host: 10252
      c.vm.network "forwarded_port", guest: 10255, host: 10255
  end

  # Kubernetes worker
  config.vm.define "worker" do |worker|
      customize_vm worker, $vm_node_mem

      worker.vm.hostname = "worker"
      worker.vm.network "private_network", ip: "192.168.77.20"
      worker.vm.network "forwarded_port", guest: 10250, host: 11250
      worker.vm.network "forwarded_port", guest: 10255, host: 11255
  end
end

