# -*- mode: ruby -*-
# vi: set ft=ruby :

$USER_NAME = 'as'
$CPU_COUNT = 4
$RAM_COUNT = "4096"
#$CPU_COUNT = 2 
#$RAM_COUNT = "2048"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.cpus = $CPU_COUNT
    vb.memory = $RAM_COUNT
  end

  config.vm.provision "shell", inline: "sudo apt-get update"
  config.vm.provision :shell, :path => "setup.sh", :args => [$USER_NAME]

  config.landrush.enabled = true
  config.vm.define "uk8s" do |c|
      c.vm.hostname = "uk8s.vagrant.test"
      c.vm.network "private_network", ip: "192.168.111.100"
      c.vm.network "forwarded_port", guest: 30000, host: 30000
  end
#  config.vm.hostname = "ubuntu-gnome.vagrant.test"
#  config.landrush.host 'static1.example.com', '1.2.3.4'
#  config.landrush.host 'static2.example.com', '2.3.4.5'
  config.landrush.host 'chees1.minikube.test', '192.168.111.100'
  config.landrush.host 'chees2.minikube.test', '192.168.111.100'
end

