# -*- mode: ruby -*-
# vi: set ft=ruby :

$USER_NAME = 'as'
$CPU_COUNT = 4
$RAM_COUNT = "4096"

Vagrant.configure("2") do |config|
  config.vm.box = "eaguirrezaba001/as"
  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.cpus = $CPU_COUNT
    vb.memory = $RAM_COUNT
  end
  config.ssh.username = "ubuntu"

  config.vm.provision "shell", inline: "sudo apt-get update"

  config.landrush.enabled = true
  config.vm.define "uk8s" do |c|
      c.vm.hostname = "uk8s.vagrant.test"
      c.vm.network "private_network", ip: "192.168.111.100"
# for access dashboard outside the box, if it is possible
#      c.vm.network "forwarded_port", guest: 30000, host: 30000
  end
  config.landrush.host 'chees1.minikube.test', '192.168.111.100'
  config.landrush.host 'chees2.minikube.test', '192.168.111.100'
end
