version: '3'

services:
  proxy:
    image: traefik
    restart: always
    networks:
      - traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/etc/traefik/traefik.toml

networks:
  traefik:
    external:
      name: traefik
